### ISSUE TITLE
Transformar Logger.dummy_task em lazy

### ISSUE THREAD

**Issue by daltonmatos** [B2W-BIT/aiologger#32]
O construtor do `aiologger.Logger` chama `asyncio.get_event_loop()`. Isso é um problema pois estamos pegando uma referência ao loop mas **antes** de efetivamente termos um loop rodando. 

Como o `aiologger` é uma lib não é ela quem liga o loop de eventos. Isso significa que se alguém ligar um loop diferente do loop retornado pelo `asyncio.get_event_loop()` teremos problemas, pois as chamadas ao logger estarão em um loop de eventos diferente do principal.

Essa implementação é analoga à desse PR: https://github.com/B2W-BIT/aiologger/pull/30

**Comment by diogommartins** [comment]
Closed at [0bd4fb](https://github.com/B2W-BIT/aiologger/pull/30/commits/0bd4fb26b18f5e871d7978524c1740f2802a4d91)
