### ISSUE TITLE
Correct shutdown

### ISSUE THREAD

**Issue by decaz** [B2W-BIT/aiologger#56]
I'm using `Logger.with_default_handlers` and see following warnings on application exit:
```
/usr/lib/python3.6/logging/__init__.py:1943: RuntimeWarning: coroutine 'AsyncStreamHandler.flush' was never awaited
  h.flush()
/usr/lib/python3.6/logging/__init__.py:1944: RuntimeWarning: coroutine 'AsyncStreamHandler.close' was never awaited
  h.close()
```
I've found there is the `shutdown` function within `logging` module which is called on application exit:
https://github.com/python/cpython/blob/3fe7fa316f74ed630fbbcdf54564f15cda7cb045/Lib/logging/__init__.py#L2118-L2119

I guess it can be got around either by making possible to call `AsyncStreamHandler.flush` and `AsyncStreamHandler.close` synchronously or by excluding `AsyncStreamHandler` from automatic cleanup by `logging` module (it's done by https://github.com/python/cpython/blob/3fe7fa316f74ed630fbbcdf54564f15cda7cb045/Lib/logging/__init__.py#L880-L881).

**Comment by graingert** [comment]
@diogommartins I think in general it may be best not to sublcass Logger as it has a lot of undesirable behaviour for asyncio

**Comment by devKurieita** [comment]
> 
> 
> @diogommartins I think in general it may be best not to sublcass Logger as it has a lot of undesirable behaviour for asyncio

I have a similar issue above except even when I don't subclass the main Logger class I still get the errors above. My original plan was to edit aiologger and add features that isn't available that I needed but for some reason I am unable to run simple examples that was found in the README.

**Comment by diogommartins** [comment]
> @diogommartins I think in general it may be best not to sublcass Logger as it has a lot of undesirable behaviour for asyncio

Hi @grainbert,

Thank you for your interest in aiologger :)

I agree that removing logging dependency is the best path and I'm working on doing so. Sorry for taking too long to reply

**Comment by diogommartins** [comment]
> > @diogommartins I think in general it may be best not to sublcass Logger as it has a lot of undesirable behaviour for asyncio
> 
> I have a similar issue above except even when I don't subclass the main Logger class I still get the errors above. My original plan was to edit aiologger and add features that isn't available that I needed but for some reason I am unable to run simple examples that was found in the README.
> 
Hi @devKurieita,
I'm sorry to hear that you had a bad experience with aiologger. Could you tell me which examples aren't working for you and what are the unexpected behaviours of those examples? 

> EDIT: Probably worth mentioning that I tried using the master and release 0.4.0-rc1. Both gives me similar results. I think I tried using a very outdated version as well that I think worked. How would I go about fixing this?

Even through aiologger is still on Beta, it is used in production in many applications and I'm surprised to hear that you encountered problems unrelated with the shutdown. Do you mind sharing some code of your use of aiologger?
