### ISSUE TITLE
Add a lazy async initialization for default handlers

### ISSUE THREAD

**Issue by diogommartins** [B2W-BIT/aiologger#6]
The current implementation depends on a running event loop:
```python
import asyncio
from aiologger import Logger

async def main():
    logger = await Logger.with_default_handlers(name='my-logger')    
    await logger.debug("Hello stdout !")

loop = asyncio.get_event_loop()
loop.run_until_complete(main())
loop.close()

```

It would be nice to be able to do something like:

```python
import asyncio
from aiologger import Logger

logger = Logger.with_default_handlers(name='my-logger')

async def main():
    # Handlers aren't initialized
    await logger.debug("First log!")  # Initialize and log
    await logger.debug("Second log!")  # just log


loop = asyncio.get_event_loop()
loop.run_until_complete(main())
loop.close()

```

**Comment by diogommartins** [comment]
@daltonmatos descrevi bem a sua ideia ?

**Comment by dnp1** [comment]
My first question is, "when shutdown should be called."

I was thinking about calling it - if it was not called before - using [atexit.register](https://docs.python.org/3.6/library/atexit.html) or in a `__del__` destructor.

But I'm open to suggestions and actively looking for alternatives.

I do not really understand implications of `__del__` usage. If I remember correctly there's no guarantees about `__del__` being called.

On the other hand, atexit is called unless SIGKILL is sent to the process (I've tested it against SIGTERM or SIGINT and it's called correctly).

**Comment by diogommartins** [comment]
@dnp1 Why do you think that shutdown implementation should change ? Even through it would be usefull, I don't see the relation of a lazy initialization with an auto shutdown and we could tackle it on another issue

**Comment by daltonmatos** [comment]
@diogommartins, @dnp1

What shutdown are you talking about? Shouldn't this be a responsibility of whoever created the loop?

**Comment by daltonmatos** [comment]
@diogommartins,

That's the idea.

**Comment by dnp1** [comment]
You both are right. The shutdown is another topic.
