### ISSUE TITLE
how to change file output format

### ISSUE THREAD

**Issue by GenaKoveshnikov** [B2W-BIT/aiologger#60]
I can't found examples about how to right use formatter. I can try use it like this but it doesn't work. How can I format log output for file handler? 

```python
from aiologger import Logger
from aiologger.handlers.files import (
    AsyncTimedRotatingFileHandler, RolloverInterval
)
from tempfile import NamedTemporaryFile
import logging


class LoggerService():

    def __init__(self):
        temp_file = NamedTemporaryFile()
        print(temp_file.name)
        formatter = logging.Formatter(
            "%(levelname)05s [%(asctime)s.%(msecs)03d][%(module)s:%(lineno)d][%(user_id)s]: %(message)s",
            datefmt="%Y-%m-%d %H:%M:%S")

        handler = AsyncTimedRotatingFileHandler(filename=temp_file.name,
                                                backup_count=10,
                                                when=RolloverInterval.DAYS)

        self.logger = Logger.with_default_handlers(name='my-logger', formatter=formatter)
        self.logger.addHandler(handler)

    async def info(self, user_id, msg):
        self.logger.info(msg, extra={"user_id": user_id})
```

**Comment by diogommartins** [comment]
> I can't found examples about how to right use formatter. I can try use it like this but it doesn't work. How can I format log output for file handler?
> 
> ```python
> from aiologger import Logger
> from aiologger.handlers.files import (
>     AsyncTimedRotatingFileHandler, RolloverInterval
> )
> from tempfile import NamedTemporaryFile
> import logging
> 
> 
> class LoggerService():
> 
>     def __init__(self):
>         temp_file = NamedTemporaryFile()
>         print(temp_file.name)
>         formatter = logging.Formatter(
>             "%(levelname)05s [%(asctime)s.%(msecs)03d][%(module)s:%(lineno)d][%(user_id)s]: %(message)s",
>             datefmt="%Y-%m-%d %H:%M:%S")
> 
>         handler = AsyncTimedRotatingFileHandler(filename=temp_file.name,
>                                                 backup_count=10,
>                                                 when=RolloverInterval.DAYS)
> 
>         self.logger = Logger.with_default_handlers(name='my-logger', formatter=formatter)
>         self.logger.addHandler(handler)
> 
>     async def info(self, user_id, msg):
>         self.logger.info(msg, extra={"user_id": user_id})
> ```

Hi @GenaKoveshnikov, thank you for your interest in aiologger. 
You made me notice that the file handlers are missing a formatter initialization argument and I'm willing to fix that. Currently, you should be able to change the handler formatter by chaging you code into something like:

```python
          formatter = logging.Formatter(
            "%(levelname)05s [%(asctime)s.%(msecs)03d][%(module)s:%(lineno)d][%(user_id)s]: %(message)s",
            datefmt="%Y-%m-%d %H:%M:%S")

        handler = AsyncTimedRotatingFileHandler(filename=temp_file.name,
                                                backup_count=10,
                                                when=RolloverInterval.DAYS)
        handler.formatter = formatter
        self.logger = Logger.with_default_handlers(name='my-logger', formatter=formatter)
        self.logger.addHandler(handler)
```

**Comment by GenaKoveshnikov** [comment]
Thanks!

**Comment by danielcloran** [comment]
Worth a mention for anyone new stumbling across this,` logger.addHandler(handler)` now follows the PEP: 8 recommendation,` logger.add_handler(handler)`.
