### ISSUE TITLE
I wrote a AsyncHTTPHandler

### ISSUE THREAD

**Issue by v5yangzai** [B2W-BIT/aiologger#73]
Hey：
    I wrote a HTTPHandler based on aiologger。Take a look, please。I am a rookie。
url: https://github.com/v5yangzai/aiologger_async_HTTPHandler

**Comment by daltonmatos** [comment]
That's awesome @v5yangzai! Thank you for dedicating part of your time to write this.

One tip for the code: You are creating an instance of `aiohttp.ClientSession()` oustside a coroutine and this is discouraged by the docs[1], for whatever reason.

This is a example of such a warning:
```
Creating a client session outside of coroutine
client_session: <aiohttp.client.ClientSession object at 0x7f3b19f6c320>
```

To solve this you could lazy initialize the session, inside the `emit()` coroutine.

Other than that, congratulations for the code.

**Comment by v5yangzai** [comment]
Thanks for your advice！！

**Comment by v5yangzai** [comment]
I hope to see your `HTTPHandler`。

**Comment by v5yangzai** [comment]
> That's awesome @v5yangzai! Thank you for dedicating part of your time to write this.
> 
> One tip for the code: You are creating an instance of `aiohttp.ClientSession()` oustside a coroutine and this is discouraged by the docs[1], for whatever reason.
> 
> This is a example of such a warning:
> 
> ```
> Creating a client session outside of coroutine
> client_session: <aiohttp.client.ClientSession object at 0x7f3b19f6c320>
> ```
> 
> To solve this you could lazy initialize the session, inside the `emit()` coroutine.
> 
> Other than that, congratulations for the code.

Thanks for your advice！！I hope to see your HTTPHandler。

**Comment by daltonmatos** [comment]
All right @v5yangzai. I will now close this issue, if you have any other doubts or news you can open a new one.

Thanks,
