### ISSUE TITLE
filters.FIlter.__call__: very implicit behavior 

### ISSUE THREAD

**Issue by kai3341** [B2W-BIT/aiologger#76]
https://github.com/B2W-BIT/aiologger/blob/2d6701ae601844572199389156afacca8e778eb9/aiologger/filters.py#L46

When I create `OwnFilter` class inherited from `Filter`, with own `OwnFilter.filter` method implementation, I have to define `__call__ = filter`. If I don't do it, `__call__` will refer to `filters.Filter.filter` method.

Understanding this interesting thing required ~4 debug hours. Thank a lot

**Comment by daltonmatos** [comment]
Hello @kai3341,

I'm sorry to hear that aiologger caused you any trouble. Looking at the code indeed it seems to be the wrong way of declaring the `__call__()` method. This seems to be the right way:

```python
class Filter:

  def __call__(self, record: LogRecord):
    return self.filter(record)
```

Did you discover where inside aiologger's code the filter is called via `__call__()` method? Mayble it's a good idea not to use this method and always use `filter.filer(record)` instead.

Thanks,

**Comment by kai3341** [comment]
Hi, @daltonmatos,

I don't use `__call__()` method in my code. It is used by `Filterer` class (parent class of `Logger`):
https://github.com/B2W-BIT/aiologger/blob/master/aiologger/filters.py#L86

I agree with you, i think it's good idea to use `filter.filer(record)`. And this line is the only line, which relies on `__call__()` method.

**Comment by daltonmatos** [comment]
Hello @kai3341,

Woul you confirm if #77 fixes the problem you faced?

Thanks,
